# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='电影名')),
                ('desc', models.TextField(verbose_name='电影描述')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('times', models.IntegerField(default=0, verbose_name='播放时长(分钟数)')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='喜爱人数')),
                ('image', models.ImageField(upload_to='film/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('category', models.CharField(default='大片', max_length=20, verbose_name='电影类别')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Director', verbose_name='导演')),
                ('film_reg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region.Region', verbose_name='国家地区')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='FilmResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('download', models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Film', verbose_name='电影')),
            ],
            options={
                'verbose_name': '海报资源',
                'verbose_name_plural': '海报资源',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('times', models.IntegerField(default=0, verbose_name='时长(分钟数)')),
                ('url', models.CharField(default='', max_length=200, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('film', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='film.Film', verbose_name='电影')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.CreateModel(
            name='BannerFilm',
            fields=[
            ],
            options={
                'verbose_name': '轮播电影',
                'verbose_name_plural': '轮播电影',
                'proxy': True,
                'indexes': [],
            },
            bases=('film.film',),
        ),
    ]
