# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-25 14:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='doubanId',
            field=models.IntegerField(default=0, verbose_name='豆瓣ID'),
        ),
        migrations.AddField(
            model_name='film',
            name='score',
            field=models.FloatField(default=0, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='film',
            name='desc',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='电影介绍'),
        ),
    ]
