# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180325_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='score_nums',
            field=models.ImageField(default=0, upload_to='', verbose_name='评论人数'),
        ),
    ]
