# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_score_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='score_nums',
            field=models.IntegerField(default=0, verbose_name='评论人数'),
        ),
    ]
