# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20180326_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ban_word', models.CharField(max_length=100, verbose_name='敏感词')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
            },
        ),
    ]
