# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 16:38
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film_article',
            fields=[
                ('url_object_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='url地址ID')),
                ('url', models.CharField(default='', max_length=300, verbose_name='url地址')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('front_image_url', models.CharField(default='', max_length=300, verbose_name='图片地址')),
                ('create_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('article', DjangoUeditor.models.UEditorField(default='', verbose_name='文章介绍')),
            ],
        ),
    ]
