# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_article',
            name='front_image_name',
            field=models.CharField(default='', max_length=300, verbose_name='图片名字'),
        ),
    ]
