# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 23:30
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_film_article_front_image_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film_article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='film_article',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='film_article',
            name='article',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章'),
        ),
    ]
