# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180331_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerArticle',
            fields=[
            ],
            options={
                'verbose_name': '轮播文章',
                'verbose_name_plural': '轮播文章',
                'proxy': True,
                'indexes': [],
            },
            bases=('article.film_article',),
        ),
        migrations.AddField(
            model_name='film_article',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
